version: '3.8'

services:
  web:
    build:
      context: .
    mem_limit: 1024m
    ports:
      - "8000:8000"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - redis
      - celery
    volumes:
      - /home/deployuser/data:/app/data/
      - /logs:/app/logs      

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery
    command: celery -A ai_intrusion_detector worker --loglevel=info
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0
    volumes:
      - /home/deployuser/data:/app/data/
      - /logs:/app/logs 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus yapılandırması
    ports:
      - "9090:9090"  # Prometheus web arayüzü
    networks:
      - monitoring

  celery-exporter:
    image: oliver006/celery-prometheus-exporter
    ports:
      - "8888:8888"  # Exporter’ın çalıştığı port
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0
    depends_on:
      - redis
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana web arayüzü
    volumes:
      - grafana-data:/var/lib/grafana  # Grafana veri depolama
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring:
