version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    cnetwork_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - .:/web
    # environment:
    #   - DJANGO_SETTINGS_MODULE=project_name.settings
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # depends_on:
    #   - db

  # db:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data

# volumes:
#   pg_data:
