services:
  web:
    build:
      context: .
    mem_limit: 1024m  # Increase as needed
    ports:
      - "8000:8000"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /home/deployuser/data:/app/data/  # Mount host directory to container directory
