version: '3.8'

services:
  web:
    build:
      context: .
    mem_limit: 1024m
    ports:
      - "8000:8000"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - redis
      - celery
    volumes:
      - /home/deployuser/data:/app/data/

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery
    command: celery -A ai_intrusion_detector worker --loglevel=info
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0
    volumes:
      - /home/deployuser/data:/app/data/
